export const projectData = [
  {
    id: 1,
    name: "NendoNest",
    image: "/images/NendoNest.jpg",
    year: 2023,
    classification: "E-commerce",
    technologies: ["react", "tailwindcss", "firebase"],
    bgColor: "#E8E8E8",
  },
  {
    id: 2,
    name: "IgniteFitter",
    image: "/images/IgniteFitter.jpg",
    year: 2024,
    classification: "Personal Training",
    technologies: ["react", "tailwindcss"],
    bgColor: "#FCF9ED",
  },
  {
    id: 3,
    name: "ZeroCuisine",
    image: "/images/ZeroCuisine.jpg",
    year: 2024,
    classification: "Dining Service",
    technologies: ["react", "tailwindcss", "nodejs", "express"],
    bgColor: "#EBDFCC",
  },
  {
    id: 4,
    name: "SparkStep",
    image: "/images/SparkStep.jpg",
    year: 2024,
    classification: "Energy Monitoring",
    technologies: ["nextjs", "tailwindcss", "typescript"],
    bgColor: "#E8E8E8",
  },

  {
    id: 5,
    name: "Pokedex",
    image: "/images/Pokedex.JPG",
    year: 2024,
    classification: "Digital Encyclopedia",
    technologies: ["nextjs", "tailwindcss", "typescript"],
    bgColor: "#C0CCC2",
  },
  {
    id: 6,
    name: "OUTLAND",
    image: "/images/OUTLAND.JPG",
    year: 2023,
    classification: "Adventure Planning",
    technologies: ["react", "tailwindcss"],
    bgColor: "#A9A8AD",
  },
];
