import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PageContextProvider from "@/context/PageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-dennis`}>
        <PageContextProvider>{children}</PageContextProvider>
      </body>
    </html>
  );
}
